### ISSUE TITLE
Tests descriptions files

### ISSUE THREAD

**Issue by T4rk1n** [T4rk1n/pytest-dash#46]
Writing good integrations tests for dash apps/components can be hard and requires much boilerplate.
You have to know how to deal with selenium and run a dash application in a test context.

pytest-dash aims to simplify this process by providing a way to easily run dash applications
and it's `wait_for` wrappers covers some of the difficulties of selenium.

To further decrease the need for boilerplate code, I propose a "behavioral" API to test
Dash applications. Basically defines tests files in a yaml format.

- The structure for the behavior test definition should remain simple and human readable.
- `context/event/outcome` syntax should be as readable as possible. They will be parsed and commands will be generated and executed.
- The user can define parameters to use in `state/event/outcome`.
- When a test definition file is found while running `pytest tests --driver Chrome`, tests will be generated and executed.

## Example test definition

Test definition example for the usual `test_simple_callback`:

```yaml
SimpleCallback:
    description: Test a dcc.Input callback output to a html.Div when a html.Button is clicked\
    parameters: // Optional user defined variables to use in state/event/outcomes.
        - $var1:
            description: Value to send to the input
            type: str
            default: hello world
    application:
        path: <app_path> // Dot notation path to the application to start.
        options:
            port: 8051
    context: // Given - Starting state
        - #input.value is "Initial Value"
    event: // When - Action
        - clear #input
        - enter $var1 in #input
        - click #btn
outcome: // Then - Assertions, expected results of the event
        - #output.text should be $var1

// Execute the tests
Tests:
        - SimpleCallback  // test with the default parameters
        - SimpleCallback: // test with custom parameters
            $var1: foo bar
```

## Commands

Commands are executed in order. They are categorized:

- context, initial state of the application
- event, what happen
- outcome, what to expect.

### Syntax

Mix of keywords, special characters identifiers and token parsing. 

#### Elements

Identifiers
- Find by id: prefix the `#`. Single
- Find by selector: surround with curly brackets (ie `{#elem > span}` find all span of #elem)
- Find by xpath: surround with square brackets `[//div/ul/li/a]`

Properties are accessed by putting a dot after the identifier: `#input.value`

If a keyword is found before the identifier, it will execute the corresponding command on the element.

#### Assertions

- should be -> assert equal
- should be less than
- etc...

### Custom commands

It should be possible for the user to define commands to undertake when a token is found.

`tests/conftest.py`
```python
from pytest_dash import behaviours

@behaviours.command('write {text} to {filename}')
def on_write(text, filename):
    ...
```
